branch-defaults:
  develop:
    environment: cropwise-staging
  main:
    environment: cropwise-production
  test-deployment:
    environment: cropwise-dev
    group_suffix: null
deploy:
  artifact: archive.zip
global:
  application_name: backend
  branch: null
  default_ec2_keyname: null
  default_platform: Docker
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
